// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sc_weight_fw_cpp
List sc_weight_fw_cpp(NumericMatrix Y, const double zeta, const bool intercept, NumericVector lambda, const double min_decrease, const int max_iter);
RcppExport SEXP _synthdid_sc_weight_fw_cpp(SEXP YSEXP, SEXP zetaSEXP, SEXP interceptSEXP, SEXP lambdaSEXP, SEXP min_decreaseSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< const bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type min_decrease(min_decreaseSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(sc_weight_fw_cpp(Y, zeta, intercept, lambda, min_decrease, max_iter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_synthdid_sc_weight_fw_cpp", (DL_FUNC) &_synthdid_sc_weight_fw_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_synthdid(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
