// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fw_step_cpp
NumericVector fw_step_cpp(const arma::mat& A, const arma::vec& x, const arma::vec& b, const double eta, const Rcpp::Nullable<double> alpha);
RcppExport SEXP _synthdid_fw_step_cpp(SEXP ASEXP, SEXP xSEXP, SEXP bSEXP, SEXP etaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<double> >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(fw_step_cpp(A, x, b, eta, alpha));
    return rcpp_result_gen;
END_RCPP
}
// sc_weight_fw_cpp
List sc_weight_fw_cpp(arma::mat Y, const double zeta, const bool intercept, arma::vec lambda, const double min_decrease, const int max_iter);
RcppExport SEXP _synthdid_sc_weight_fw_cpp(SEXP YSEXP, SEXP zetaSEXP, SEXP interceptSEXP, SEXP lambdaSEXP, SEXP min_decreaseSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< const bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type min_decrease(min_decreaseSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(sc_weight_fw_cpp(Y, zeta, intercept, lambda, min_decrease, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// grad_beta_cpp
NumericVector grad_beta_cpp(const NumericVector& X, const arma::vec& lambda, const arma::vec& omega, const arma::vec& err_lambda, const arma::vec& err_omega, const int N0, const int T0);
RcppExport SEXP _synthdid_grad_beta_cpp(SEXP XSEXP, SEXP lambdaSEXP, SEXP omegaSEXP, SEXP err_lambdaSEXP, SEXP err_omegaSEXP, SEXP N0SEXP, SEXP T0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type err_lambda(err_lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type err_omega(err_omegaSEXP);
    Rcpp::traits::input_parameter< const int >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< const int >::type T0(T0SEXP);
    rcpp_result_gen = Rcpp::wrap(grad_beta_cpp(X, lambda, omega, err_lambda, err_omega, N0, T0));
    return rcpp_result_gen;
END_RCPP
}
// contract3_cpp
NumericMatrix contract3_cpp(const NumericVector& X, const arma::vec& v);
RcppExport SEXP _synthdid_contract3_cpp(SEXP XSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(contract3_cpp(X, v));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_synthdid_fw_step_cpp", (DL_FUNC) &_synthdid_fw_step_cpp, 5},
    {"_synthdid_sc_weight_fw_cpp", (DL_FUNC) &_synthdid_sc_weight_fw_cpp, 6},
    {"_synthdid_grad_beta_cpp", (DL_FUNC) &_synthdid_grad_beta_cpp, 7},
    {"_synthdid_contract3_cpp", (DL_FUNC) &_synthdid_contract3_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_synthdid(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
