# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fw_step_cpp <- function(A, x, b, eta, alpha = NULL) {
    .Call(`_synthdid_fw_step_cpp`, A, x, b, eta, alpha)
}

sc_weight_fw_cpp <- function(Y, zeta, intercept, lambda, min_decrease, max_iter) {
    .Call(`_synthdid_sc_weight_fw_cpp`, Y, zeta, intercept, lambda, min_decrease, max_iter)
}

grad_beta_cpp <- function(X, lambda, omega, err_lambda, err_omega, N0, T0) {
    .Call(`_synthdid_grad_beta_cpp`, X, lambda, omega, err_lambda, err_omega, N0, T0)
}

contract3_cpp <- function(X, v) {
    .Call(`_synthdid_contract3_cpp`, X, v)
}

