# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sc_weight_fw_cpp <- function(Y, zeta, intercept, lambda, min_decrease, max_iter) {
    .Call(`_synthdid_sc_weight_fw_cpp`, Y, zeta, intercept, lambda, min_decrease, max_iter)
}

